REGEXES = ["^.*added.*to the group.$", "^.*removed.*from the group.$", 
   "^.*reacted.*to your message", "^.*scored.*in a game.",
   "^.*started a video chat.$", "^.*set the nickname for.*",
   "^https://.*", "^http://.*", ".*changed the group photo.$",
   ".*started a call.$", ".*left the group.$", ".*joined the video chat.$",
   "This poll is no longer available.", ".*sent a post.$", 
   ".*set his own nickname to.*", "^@fbchess.*", ".*set.*nickname to.*",
  "The video chat ended.", ".*added a participant.$", ".*named the group.*",
  ".*created a poll:.*", ".*voted for.*in the poll.*", ".*Hex FRVR.*", 
   ".*Basketball FRVR.*", ".*sent an attachment.$", ".*set the emoji to.*",
  ".*changed the chat theme.$", ".*responded $", ".* named the plan .*",
  ".* updated the plan .*", ".* scored .* points.*", ".* moved up the leaderboard in.*",
  "@..chess", ".* to move \(White\)$", ".* to move \(Black\)$", 
   "^You have requested an undo$", "^Last move has been undone$", "^Black wins!$",
  "^White wins!$", "^Check!$", "^Started new game as Black$", "^Started new game as White$",
  ".*set a new personal best of.*", ".*cleared.*nickname.*", ".*requested.*from.*for.*",
  ".*joined the call.$", "The call ended.", "The video call ended."]
